// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADCRnYa6BiwF70GKvDQRsD34AXzWbcfiU',
    appId: '1:336096606256:web:08dfa91b9d18aab5d995f5',
    messagingSenderId: '336096606256',
    projectId: 'flutter-todo-e5df0',
    authDomain: 'flutter-todo-e5df0.firebaseapp.com',
    storageBucket: 'flutter-todo-e5df0.firebasestorage.app',
    measurementId: 'G-N2BCN599Q7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBK-p8-Rb8tUT4cZK4BtJ34JOIoBOVGEBE',
    appId: '1:336096606256:android:fabd7352a3ce7873d995f5',
    messagingSenderId: '336096606256',
    projectId: 'flutter-todo-e5df0',
    storageBucket: 'flutter-todo-e5df0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6LXASfVcbaH4ejQkTRh9ElRXF5GjS7vo',
    appId: '1:336096606256:ios:e783a83797ebde67d995f5',
    messagingSenderId: '336096606256',
    projectId: 'flutter-todo-e5df0',
    storageBucket: 'flutter-todo-e5df0.firebasestorage.app',
    iosBundleId: 'com.example.chapter9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6LXASfVcbaH4ejQkTRh9ElRXF5GjS7vo',
    appId: '1:336096606256:ios:e783a83797ebde67d995f5',
    messagingSenderId: '336096606256',
    projectId: 'flutter-todo-e5df0',
    storageBucket: 'flutter-todo-e5df0.firebasestorage.app',
    iosBundleId: 'com.example.chapter9',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADCRnYa6BiwF70GKvDQRsD34AXzWbcfiU',
    appId: '1:336096606256:web:d716ac37e6066079d995f5',
    messagingSenderId: '336096606256',
    projectId: 'flutter-todo-e5df0',
    authDomain: 'flutter-todo-e5df0.firebaseapp.com',
    storageBucket: 'flutter-todo-e5df0.firebasestorage.app',
    measurementId: 'G-RY6XF245Q8',
  );
}
