// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKvsZDxJwstoPeLOlfFTrMHVv1YfEgwMA',
    appId: '1:665956839552:web:98c2783dc332406dca3665',
    messagingSenderId: '665956839552',
    projectId: 'flutter-rememmber',
    authDomain: 'flutter-rememmber.firebaseapp.com',
    storageBucket: 'flutter-rememmber.firebasestorage.app',
    measurementId: 'G-CWMLPLP01G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCssq1XjuAmn3ZL3x74nUIulsb7oBkW5ns',
    appId: '1:665956839552:android:9f59ae620180ba13ca3665',
    messagingSenderId: '665956839552',
    projectId: 'flutter-rememmber',
    storageBucket: 'flutter-rememmber.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9aHsQ7LauvgOhGHAtB5C6ekhLpsez3Xw',
    appId: '1:665956839552:ios:acbb5b71be082240ca3665',
    messagingSenderId: '665956839552',
    projectId: 'flutter-rememmber',
    storageBucket: 'flutter-rememmber.firebasestorage.app',
    iosBundleId: 'com.example.chapter02',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9aHsQ7LauvgOhGHAtB5C6ekhLpsez3Xw',
    appId: '1:665956839552:ios:acbb5b71be082240ca3665',
    messagingSenderId: '665956839552',
    projectId: 'flutter-rememmber',
    storageBucket: 'flutter-rememmber.firebasestorage.app',
    iosBundleId: 'com.example.chapter02',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKvsZDxJwstoPeLOlfFTrMHVv1YfEgwMA',
    appId: '1:665956839552:web:0b1ee41e50a8f869ca3665',
    messagingSenderId: '665956839552',
    projectId: 'flutter-rememmber',
    authDomain: 'flutter-rememmber.firebaseapp.com',
    storageBucket: 'flutter-rememmber.firebasestorage.app',
    measurementId: 'G-8ZRDPVRL1T',
  );
}
