// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_P65eSTNcZdJq5dl3ppal5PXX0tsIhes',
    appId: '1:438290631834:web:60278bdc4f43300733e323',
    messagingSenderId: '438290631834',
    projectId: 'flutter-chat-fa753',
    authDomain: 'flutter-chat-fa753.firebaseapp.com',
    storageBucket: 'flutter-chat-fa753.firebasestorage.app',
    measurementId: 'G-58ZC827P23',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrCMea58OA7_ZeUT9JMOJlj4SD-zC9dwc',
    appId: '1:438290631834:android:026a41f11be8577733e323',
    messagingSenderId: '438290631834',
    projectId: 'flutter-chat-fa753',
    storageBucket: 'flutter-chat-fa753.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4coSpNGVNF2O_WemcG_jOK5W2-VHo_k8',
    appId: '1:438290631834:ios:eaa49c7ea5cae44a33e323',
    messagingSenderId: '438290631834',
    projectId: 'flutter-chat-fa753',
    storageBucket: 'flutter-chat-fa753.firebasestorage.app',
    iosBundleId: 'com.example.chapter10',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4coSpNGVNF2O_WemcG_jOK5W2-VHo_k8',
    appId: '1:438290631834:ios:eaa49c7ea5cae44a33e323',
    messagingSenderId: '438290631834',
    projectId: 'flutter-chat-fa753',
    storageBucket: 'flutter-chat-fa753.firebasestorage.app',
    iosBundleId: 'com.example.chapter10',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_P65eSTNcZdJq5dl3ppal5PXX0tsIhes',
    appId: '1:438290631834:web:04ce0d610e05025233e323',
    messagingSenderId: '438290631834',
    projectId: 'flutter-chat-fa753',
    authDomain: 'flutter-chat-fa753.firebaseapp.com',
    storageBucket: 'flutter-chat-fa753.firebasestorage.app',
    measurementId: 'G-EB5LXBL1PW',
  );
}
